sudo: false

language: java

jdk:
  - oraclejdk8

install: mvn -B -e -X install -U -DskipTests=true

script: mvn -B -e -X verify -U -Dmaven.javadoc.skip=true -Dmaven.groovydoc.skip=true

after_success:

cache:
  directories:
  - $HOME/.m2

env:
  global:

branches:
  only:
    - master
    - /^release.*$/
